"""Map a running executable's basename to a human-friendly display name.

Used by the tray's recording-toast so the subtitle reads "Elden Ring is being
recorded" rather than "eldenring is being recorded". A manual lookup covers
the popular titles (where the exe name is opaque, e.g. ``r5apex`` → Apex
Legends, ``ffxiv_dx11`` → FFXIV); anything not in the table falls back to a
small heuristic that strips the .exe + common launcher suffixes, splits
camelCase / snake_case, and title-cases the result.

Lookup is case-insensitive on the exe key.
"""

from __future__ import annotations

import re

# --- explicit lookup ---
# Keys are matched case-insensitively. Add liberally — false positives are
# impossible (we only match exact basenames), missing entries just mean a less
# polished label.
_DISPLAY_NAMES: dict[str, str] = {
    # FromSoftware / soulslikes
    "eldenring.exe": "Elden Ring",
    "darksoulsiii.exe": "Dark Souls III",
    "darksoulsii.exe": "Dark Souls II",
    "darksouls.exe": "Dark Souls",
    "sekiro.exe": "Sekiro: Shadows Die Twice",
    "bloodborne.exe": "Bloodborne",
    "nioh2.exe": "Nioh 2",
    "nioh.exe": "Nioh",
    "wo long.exe": "Wo Long: Fallen Dynasty",
    "wolongfallendynasty.exe": "Wo Long: Fallen Dynasty",
    "liesofp.exe": "Lies of P",
    "code_vein.exe": "Code Vein",
    "remnant2.exe": "Remnant II",
    "remnantfromtheashes.exe": "Remnant: From the Ashes",
    "lordsofthefallen.exe": "Lords of the Fallen",
    "lotf2.exe": "Lords of the Fallen",
    "mortal shell.exe": "Mortal Shell",
    "blasphemous.exe": "Blasphemous",
    "blasphemous2.exe": "Blasphemous II",
    "stray-blade.exe": "Stray Blade",

    # MMO
    "ffxiv.exe": "Final Fantasy XIV",
    "ffxiv_dx11.exe": "Final Fantasy XIV",
    "ffxiv_boot.exe": "Final Fantasy XIV",
    "ffxivlauncher.exe": "Final Fantasy XIV",
    "wow.exe": "World of Warcraft",
    "wowclassic.exe": "World of Warcraft Classic",
    "gw2.exe": "Guild Wars 2",
    "gw2-64.exe": "Guild Wars 2",
    "guild wars 2.exe": "Guild Wars 2",
    "eso.exe": "Elder Scrolls Online",
    "eso64.exe": "Elder Scrolls Online",
    "blackdesert64.exe": "Black Desert Online",
    "lost ark.exe": "Lost Ark",
    "lostark.exe": "Lost Ark",
    "runelite.exe": "RuneScape",
    "jagexlauncher.exe": "RuneScape",
    "oldschool.exe": "Old School RuneScape",
    "osrs.exe": "Old School RuneScape",
    "newworld.exe": "New World",
    "tera.exe": "TERA",
    "everquest.exe": "EverQuest",
    "rift.exe": "RIFT",
    "starcitizen.exe": "Star Citizen",
    "throne and liberty.exe": "Throne and Liberty",
    "swtor.exe": "Star Wars: The Old Republic",
    "pathofexile.exe": "Path of Exile",
    "pathofexilesteam.exe": "Path of Exile",
    "pathofexile_x64steam.exe": "Path of Exile",
    "pathofexile_x64.exe": "Path of Exile",
    "pathofexile2.exe": "Path of Exile 2",

    # MOBA
    "leagueclient.exe": "League of Legends",
    "league of legends.exe": "League of Legends",
    "riotclientservices.exe": "Riot Client",
    "dota2.exe": "Dota 2",
    "hots.exe": "Heroes of the Storm",
    "smite.exe": "SMITE",
    "smite2.exe": "SMITE 2",
    "pokemon unite.exe": "Pokémon Unite",
    "deadlock.exe": "Deadlock",

    # Shooters / battle royale
    "valorant.exe": "Valorant",
    "valorant-win64-shipping.exe": "Valorant",
    "cs2.exe": "Counter-Strike 2",
    "csgo.exe": "Counter-Strike: Global Offensive",
    "fortniteclient-win64-shipping.exe": "Fortnite",
    "fortnitelauncher.exe": "Fortnite",
    "r5apex.exe": "Apex Legends",
    "r5apex_dx12.exe": "Apex Legends",
    "pubg.exe": "PUBG: Battlegrounds",
    "tslgame.exe": "PUBG: Battlegrounds",
    "destinylauncher.exe": "Destiny 2",
    "destiny2.exe": "Destiny 2",
    "overwatch.exe": "Overwatch 2",
    "rainbowsix.exe": "Rainbow Six Siege",
    "rainbowsix_vulkan.exe": "Rainbow Six Siege",
    "rainbowsixsiege.exe": "Rainbow Six Siege",
    "modernwarfare.exe": "Call of Duty: Modern Warfare",
    "modernwarfare2.exe": "Call of Duty: Modern Warfare II",
    "modernwarfare3.exe": "Call of Duty: Modern Warfare III",
    "codmw.exe": "Call of Duty: Modern Warfare",
    "codmw2.exe": "Call of Duty: Modern Warfare II",
    "cod.exe": "Call of Duty",
    "blackops6.exe": "Call of Duty: Black Ops 6",
    "blackops4.exe": "Call of Duty: Black Ops 4",
    "blackopscoldwar.exe": "Call of Duty: Black Ops Cold War",
    "vanguard.exe": "Call of Duty: Vanguard",
    "iw7_ship.exe": "Call of Duty",
    "iw8_ship.exe": "Call of Duty",
    "warzone.exe": "Call of Duty: Warzone",
    "battlefield 2042.exe": "Battlefield 2042",
    "bf2042.exe": "Battlefield 2042",
    "bf1.exe": "Battlefield 1",
    "battlefieldv.exe": "Battlefield V",
    "bfv.exe": "Battlefield V",
    "battlefield4.exe": "Battlefield 4",
    "bf4.exe": "Battlefield 4",
    "marvelrivals_launcher.exe": "Marvel Rivals",
    "marvelrivals.exe": "Marvel Rivals",
    "marvelrivals-win64-shipping.exe": "Marvel Rivals",
    "thefinals.exe": "The Finals",
    "discovery-win64-shipping.exe": "The Finals",
    "deltaforce.exe": "Delta Force",
    "deltaforce-win64-shipping.exe": "Delta Force",
    "escapefromtarkov.exe": "Escape from Tarkov",
    "eft.exe": "Escape from Tarkov",
    "escapefromtarkov_be.exe": "Escape from Tarkov",
    "arenabreakoutinfinite.exe": "Arena Breakout: Infinite",
    "hunt.exe": "Hunt: Showdown",
    "huntshowdown.exe": "Hunt: Showdown",
    "hunt-win64-shipping.exe": "Hunt: Showdown",
    "grayzonewarfare.exe": "Gray Zone Warfare",
    "doometernal.exe": "DOOM Eternal",
    "doometernalx64vk.exe": "DOOM Eternal",
    "doom.exe": "DOOM",
    "doomx64vk.exe": "DOOM",
    "doomthedarkages.exe": "DOOM: The Dark Ages",
    "titanfall2.exe": "Titanfall 2",
    "chivalrymw.exe": "Chivalry: Medieval Warfare",
    "mordhau-win64-shipping.exe": "Mordhau",
    "splitgate.exe": "Splitgate",
    "splitgate2.exe": "Splitgate 2",
    "quakechampions.exe": "Quake Champions",
    "halo.exe": "Halo",
    "mcc-win64-shipping.exe": "Halo: The Master Chief Collection",
    "haloreach.exe": "Halo: Reach",
    "haloinfinite.exe": "Halo Infinite",
    "paladinsclient.exe": "Paladins",
    "planetside2.exe": "PlanetSide 2",
    "warframe.exe": "Warframe",
    "warframe.x64.exe": "Warframe",
    "helldivers2.exe": "Helldivers 2",
    "helldivers2-win64-shipping.exe": "Helldivers 2",
    "readyornot-win64-shipping.exe": "Ready or Not",
    "groundbranch-win64-shipping.exe": "Ground Branch",
    "squad.exe": "Squad",
    "postscriptum.exe": "Post Scriptum",
    "hell let loose.exe": "Hell Let Loose",
    "hll-win64-shipping.exe": "Hell Let Loose",
    "warthunder.exe": "War Thunder",
    "wot.exe": "World of Tanks",
    "wows.exe": "World of Warships",
    "worldofwarships.exe": "World of Warships",
    "worldoftanks.exe": "World of Tanks",

    # Survival / sandbox
    "minecraft.windows.exe": "Minecraft",
    "javaw.exe": "Minecraft",  # imperfect but most common case
    "minecraftlauncher.exe": "Minecraft",
    "vrchat.exe": "VRChat",
    "rust_client.exe": "Rust",
    "rustclient.exe": "Rust",
    "dayz_x64.exe": "DayZ",
    "ark.exe": "ARK: Survival Evolved",
    "shootergame.exe": "ARK: Survival Evolved",
    "arkascended.exe": "ARK: Survival Ascended",
    "palworld-win64-shipping.exe": "Palworld",
    "palworld.exe": "Palworld",
    "valheim.exe": "Valheim",
    "terraria.exe": "Terraria",
    "stardew valley.exe": "Stardew Valley",
    "stardewvalley.exe": "Stardew Valley",
    "satisfactory-win64-shipping.exe": "Satisfactory",
    "factorygame-win64-shipping.exe": "Satisfactory",
    "subnautica.exe": "Subnautica",
    "subnauticazero.exe": "Subnautica: Below Zero",
    "theforest.exe": "The Forest",
    "endnightgame.exe": "The Forest",
    "sonsoftheforest.exe": "Sons of the Forest",
    "sonsoftheforest-win64-shipping.exe": "Sons of the Forest",
    "grounded.exe": "Grounded",
    "project zomboid64.exe": "Project Zomboid",
    "projectzomboid64.exe": "Project Zomboid",
    "thelongdark.exe": "The Long Dark",
    "green hell.exe": "Green Hell",
    "greenhell.exe": "Green Hell",
    "icarus.exe": "Icarus",
    "enshrouded.exe": "Enshrouded",
    "nightingaleclient-win64-shipping.exe": "Nightingale",
    "soulmask-win64-shipping.exe": "Soulmask",
    "once human.exe": "Once Human",
    "oncehumanclient.exe": "Once Human",
    "7daystodie.exe": "7 Days to Die",
    "conan.exe": "Conan Exiles",
    "conansandbox.exe": "Conan Exiles",
    "no man's sky.exe": "No Man's Sky",
    "nms.exe": "No Man's Sky",
    "nmsse.exe": "No Man's Sky",

    # AAA action / open world
    "gta5.exe": "Grand Theft Auto V",
    "gtav.exe": "Grand Theft Auto V",
    "gtavlauncher.exe": "Grand Theft Auto V",
    "gta6.exe": "Grand Theft Auto VI",
    "rdr2.exe": "Red Dead Redemption 2",
    "rdr.exe": "Red Dead Redemption",
    "maxpayne3.exe": "Max Payne 3",
    "cyberpunk2077.exe": "Cyberpunk 2077",
    "witcher3.exe": "The Witcher 3",
    "witcher.exe": "The Witcher",
    "witcher2.exe": "The Witcher 2",
    "bg3.exe": "Baldur's Gate 3",
    "bg3_dx11.exe": "Baldur's Gate 3",
    "divinityoriginalsin2.exe": "Divinity: Original Sin 2",
    "dos2.exe": "Divinity: Original Sin 2",
    "divinityoriginalsin.exe": "Divinity: Original Sin",
    "starfield.exe": "Starfield",
    "fallout4.exe": "Fallout 4",
    "fallout76.exe": "Fallout 76",
    "fallout3.exe": "Fallout 3",
    "falloutnv.exe": "Fallout: New Vegas",
    "skyrim.exe": "Skyrim",
    "skyrimse.exe": "Skyrim Special Edition",
    "skyrimvr.exe": "Skyrim VR",
    "tesv.exe": "Skyrim",
    "oblivion.exe": "Oblivion",
    "oblivionremastered.exe": "Oblivion Remastered",
    "oblivion-win64-shipping.exe": "Oblivion Remastered",
    "hogwartslegacy.exe": "Hogwarts Legacy",
    "hogwartslegacy_dx12.exe": "Hogwarts Legacy",
    "spider-man.exe": "Marvel's Spider-Man",
    "spider-man2.exe": "Marvel's Spider-Man 2",
    "miles.exe": "Marvel's Spider-Man: Miles Morales",
    "godofwar.exe": "God of War",
    "gowr.exe": "God of War Ragnarök",
    "ghostoftsushima.exe": "Ghost of Tsushima",
    "ac-mirage.exe": "Assassin's Creed Mirage",
    "acshadows.exe": "Assassin's Creed Shadows",
    "assassinscreedshadows.exe": "Assassin's Creed Shadows",
    "acodyssey.exe": "Assassin's Creed Odyssey",
    "acvalhalla.exe": "Assassin's Creed Valhalla",
    "acorigins.exe": "Assassin's Creed Origins",
    "acbrotherhood.exe": "Assassin's Creed Brotherhood",
    "acunity.exe": "Assassin's Creed Unity",
    "acsyndicate.exe": "Assassin's Creed Syndicate",
    "dragons dogma 2.exe": "Dragon's Dogma 2",
    "dd2.exe": "Dragon's Dogma 2",
    "dragonsdogma.exe": "Dragon's Dogma",
    "monsterhunterwilds.exe": "Monster Hunter Wilds",
    "mhwilds.exe": "Monster Hunter Wilds",
    "mhrise.exe": "Monster Hunter Rise",
    "mhworld.exe": "Monster Hunter: World",
    "dragonage.exe": "Dragon Age",
    "dragonageinquisition.exe": "Dragon Age: Inquisition",
    "dragonageveilguard.exe": "Dragon Age: The Veilguard",
    "veilguard-win64-shipping.exe": "Dragon Age: The Veilguard",
    "masseffect.exe": "Mass Effect",
    "masseffect2.exe": "Mass Effect 2",
    "masseffect3.exe": "Mass Effect 3",
    "mele.exe": "Mass Effect Legendary Edition",
    "masseffectandromeda.exe": "Mass Effect: Andromeda",
    "dyinglight.exe": "Dying Light",
    "dyinglightgame.exe": "Dying Light",
    "dyinglightgame_x64_rwdi.exe": "Dying Light",
    "dyinglight2.exe": "Dying Light 2",
    "deadspace.exe": "Dead Space",
    "callisto.exe": "The Callisto Protocol",
    "callisto-win64-shipping.exe": "The Callisto Protocol",
    "residentevil2.exe": "Resident Evil 2",
    "residentevil3.exe": "Resident Evil 3",
    "residentevil4.exe": "Resident Evil 4",
    "residentevil7.exe": "Resident Evil 7",
    "residentevilvillage.exe": "Resident Evil Village",
    "re2.exe": "Resident Evil 2",
    "re3.exe": "Resident Evil 3",
    "re4.exe": "Resident Evil 4",
    "re7.exe": "Resident Evil 7",
    "re8.exe": "Resident Evil Village",
    "returnal.exe": "Returnal",
    "returnalsteam.exe": "Returnal",
    "controlgame.exe": "Control",
    "control.exe": "Control",
    "alanwake2.exe": "Alan Wake 2",
    "senua.exe": "Hellblade: Senua's Sacrifice",
    "hellbladesenua.exe": "Hellblade: Senua's Sacrifice",
    "hellblade2.exe": "Senua's Saga: Hellblade II",
    "dishonoreddeathoftheoutsider.exe": "Dishonored: Death of the Outsider",
    "dishonored2.exe": "Dishonored 2",
    "prey.exe": "Prey",
    "deathloop.exe": "Deathloop",
    "metalgearsolidv.exe": "Metal Gear Solid V",
    "mgsvtpp.exe": "Metal Gear Solid V: The Phantom Pain",
    "mgsdelta.exe": "Metal Gear Solid Δ: Snake Eater",
    "indiana.exe": "Indiana Jones and the Great Circle",
    "indianajonesgreatcircle.exe": "Indiana Jones and the Great Circle",
    "blackmyth_wukong.exe": "Black Myth: Wukong",
    "blackmythwukong.exe": "Black Myth: Wukong",
    "b1-win64-shipping.exe": "Black Myth: Wukong",
    "stalker2.exe": "S.T.A.L.K.E.R. 2",
    "stalker2-win64-shipping.exe": "S.T.A.L.K.E.R. 2",
    "atomfall.exe": "Atomfall",
    "avowed.exe": "Avowed",
    "sea of thieves.exe": "Sea of Thieves",
    "sotgame.exe": "Sea of Thieves",

    # Racing / sim
    "f1_24.exe": "F1 24",
    "f1_23.exe": "F1 23",
    "f124.exe": "F1 24",
    "f123.exe": "F1 23",
    "f1_22.exe": "F1 22",
    "f1_25.exe": "F1 25",
    "iracingsim64dx12.exe": "iRacing",
    "iracing.exe": "iRacing",
    "ac2-win64-shipping.exe": "Assetto Corsa Competizione",
    "assettocorsa.exe": "Assetto Corsa",
    "acs.exe": "Assetto Corsa",
    "rfactor2.exe": "rFactor 2",
    "flightsimulator.exe": "Microsoft Flight Simulator",
    "microsoftflightsimulator.exe": "Microsoft Flight Simulator",
    "flightsimulator2024.exe": "Microsoft Flight Simulator 2024",
    "fs2024.exe": "Microsoft Flight Simulator 2024",
    "eurotrucksim2.exe": "Euro Truck Simulator 2",
    "ets2.exe": "Euro Truck Simulator 2",
    "americantrucksim.exe": "American Truck Simulator",
    "ats.exe": "American Truck Simulator",
    "forzahorizon5.exe": "Forza Horizon 5",
    "forzahorizon4.exe": "Forza Horizon 4",
    "forzamotorsport.exe": "Forza Motorsport",
    "forzahorizon5steam.exe": "Forza Horizon 5",
    "forzahorizon4steam.exe": "Forza Horizon 4",
    "beamng.drive.exe": "BeamNG.drive",
    "beamng.exe": "BeamNG.drive",
    "beamng.tech.exe": "BeamNG.tech",
    "rocketleague.exe": "Rocket League",
    "thecrew2.exe": "The Crew 2",
    "thecrewmotorfest.exe": "The Crew Motorfest",
    "fifa23.exe": "FIFA 23",
    "fifa24.exe": "EA Sports FC 24",
    "fc24.exe": "EA Sports FC 24",
    "fc25.exe": "EA Sports FC 25",
    "eafc.exe": "EA Sports FC",
    "nba2k24.exe": "NBA 2K24",
    "nba2k25.exe": "NBA 2K25",
    "madden24.exe": "Madden NFL 24",
    "madden25.exe": "Madden NFL 25",
    "mlbtheshow.exe": "MLB The Show",
    "granturismo7.exe": "Gran Turismo 7",
    "wrc.exe": "EA Sports WRC",
    "easportswrc.exe": "EA Sports WRC",
    "dirtrally2.0.exe": "DiRT Rally 2.0",
    "dirtrally.exe": "DiRT Rally",
    "snowrunner.exe": "SnowRunner",
    "mudrunner.exe": "MudRunner",
    "tonyhawkproskater.exe": "Tony Hawk's Pro Skater",
    "thps.exe": "Tony Hawk's Pro Skater",
    "skater xl.exe": "Skater XL",
    "skaterxl.exe": "Skater XL",
    "session.exe": "Session: Skate Sim",

    # Fighters
    "tekken8.exe": "Tekken 8",
    "tekken7.exe": "Tekken 7",
    "polarislauncher-win64-shipping.exe": "Tekken 8",
    "sf6.exe": "Street Fighter 6",
    "streetfighter6.exe": "Street Fighter 6",
    "streetfighterv.exe": "Street Fighter V",
    "sfv.exe": "Street Fighter V",
    "mk1.exe": "Mortal Kombat 1",
    "mk11.exe": "Mortal Kombat 11",
    "mortalkombat11.exe": "Mortal Kombat 11",
    "mortalkombat1.exe": "Mortal Kombat 1",
    "dbfighterz.exe": "Dragon Ball FighterZ",
    "dragonballsparkingzero.exe": "Dragon Ball: Sparking! Zero",
    "guiltygearstrive.exe": "Guilty Gear -Strive-",
    "ggstrive-win64-shipping.exe": "Guilty Gear -Strive-",
    "granbluefantasyversusrising.exe": "Granblue Fantasy Versus: Rising",
    "gbvsr.exe": "Granblue Fantasy Versus: Rising",
    "skullgirls.exe": "Skullgirls",
    "brawlhalla.exe": "Brawlhalla",
    "multiversus.exe": "MultiVersus",
    "nsuns4.exe": "Naruto Shippuden: Ultimate Ninja Storm 4",
    "injusticegau2.exe": "Injustice 2",
    "injustice2.exe": "Injustice 2",

    # Strategy / 4X / city
    "civ7.exe": "Civilization VII",
    "civilizationvii.exe": "Civilization VII",
    "civilizationvii_dx12.exe": "Civilization VII",
    "civilizationvi.exe": "Civilization VI",
    "civ6.exe": "Civilization VI",
    "civilizationv.exe": "Civilization V",
    "aoe2de_s.exe": "Age of Empires II: Definitive Edition",
    "aoe2de.exe": "Age of Empires II: Definitive Edition",
    "aoe4_s.exe": "Age of Empires IV",
    "aoe4.exe": "Age of Empires IV",
    "stellaris.exe": "Stellaris",
    "eu5.exe": "Europa Universalis V",
    "eu4.exe": "Europa Universalis IV",
    "hoi4.exe": "Hearts of Iron IV",
    "ck3.exe": "Crusader Kings III",
    "ck2.exe": "Crusader Kings II",
    "victoria3.exe": "Victoria 3",
    "victoria2.exe": "Victoria II",
    "imperator.exe": "Imperator: Rome",
    "totalwarwarhammer3.exe": "Total War: Warhammer III",
    "totalwarwarhammer2.exe": "Total War: Warhammer II",
    "totalwarwarhammer.exe": "Total War: Warhammer",
    "warhammer3.exe": "Total War: Warhammer III",
    "totalwarrome2.exe": "Total War: Rome II",
    "totalwarthreekingdoms.exe": "Total War: Three Kingdoms",
    "pharaoh.exe": "Total War: Pharaoh",
    "troytw.exe": "A Total War Saga: Troy",
    "attilatw.exe": "Total War: Attila",
    "empire.exe": "Empire: Total War",
    "totalwarpharaohdynasties.exe": "Total War: Pharaoh — Dynasties",
    "citiesskylines2.exe": "Cities: Skylines II",
    "cities.exe": "Cities: Skylines",
    "citiesskylines.exe": "Cities: Skylines",
    "citiesskylinesii.exe": "Cities: Skylines II",
    "cities2-win64-shipping.exe": "Cities: Skylines II",
    "rimworldwin64.exe": "RimWorld",
    "rimworld.exe": "RimWorld",
    "frostpunk.exe": "Frostpunk",
    "frostpunk2.exe": "Frostpunk 2",
    "timberbornwin.exe": "Timberborn",
    "timberborn.exe": "Timberborn",
    "manor lords.exe": "Manor Lords",
    "manorlords-win64-shipping.exe": "Manor Lords",
    "dwarffortress.exe": "Dwarf Fortress",
    "anno1800.exe": "Anno 1800",
    "anno117.exe": "Anno 117",
    "tropico6.exe": "Tropico 6",
    "northgard.exe": "Northgard",
    "songs of conquest.exe": "Songs of Conquest",
    "bannerlord.exe": "Mount & Blade II: Bannerlord",
    "mountandbladebannerlord.exe": "Mount & Blade II: Bannerlord",
    "mount&bladewarband.exe": "Mount & Blade: Warband",

    # Roguelikes / metroidvanias / indies
    "hades2.exe": "Hades II",
    "hades.exe": "Hades",
    "deadcells.exe": "Dead Cells",
    "hollow knight.exe": "Hollow Knight",
    "hollow_knight.exe": "Hollow Knight",
    "silksong.exe": "Hollow Knight: Silksong",
    "hollowknightsilksong.exe": "Hollow Knight: Silksong",
    "balatrogame.exe": "Balatro",
    "balatro.exe": "Balatro",
    "slay the spire.exe": "Slay the Spire",
    "slaythespire.exe": "Slay the Spire",
    "slaythespire2.exe": "Slay the Spire 2",
    "risk of rain 2.exe": "Risk of Rain 2",
    "ror2.exe": "Risk of Rain 2",
    "riskofrain2.exe": "Risk of Rain 2",
    "riskofrainreturns.exe": "Risk of Rain Returns",
    "enter the gungeon.exe": "Enter the Gungeon",
    "enterthegungeon.exe": "Enter the Gungeon",
    "cult of the lamb.exe": "Cult of the Lamb",
    "cultofthelamb.exe": "Cult of the Lamb",
    "vampire survivors.exe": "Vampire Survivors",
    "vampiresurvivors.exe": "Vampire Survivors",
    "brotatosteam.exe": "Brotato",
    "brotato.exe": "Brotato",
    "noita.exe": "Noita",
    "spelunky2.exe": "Spelunky 2",
    "loop hero.exe": "Loop Hero",
    "loophero.exe": "Loop Hero",
    "inscryption.exe": "Inscryption",
    "caves of qud.exe": "Caves of Qud",
    "cavesofqud.exe": "Caves of Qud",
    "backpack hero.exe": "Backpack Hero",
    "backpackhero.exe": "Backpack Hero",
    "peglin.exe": "Peglin",
    "tiny tina's wonderlands.exe": "Tiny Tina's Wonderlands",
    "borderlands3.exe": "Borderlands 3",
    "borderlands2.exe": "Borderlands 2",
    "borderlandstps.exe": "Borderlands: The Pre-Sequel",
    "borderlands.exe": "Borderlands",
    "borderlands4.exe": "Borderlands 4",

    # Co-op / party
    "among us.exe": "Among Us",
    "amongus.exe": "Among Us",
    "phasmophobia.exe": "Phasmophobia",
    "lethal company.exe": "Lethal Company",
    "lethal.exe": "Lethal Company",
    "contentwarning.exe": "Content Warning",
    "contentwarning-win64-shipping.exe": "Content Warning",
    "repo.exe": "R.E.P.O.",
    "r.e.p.o.exe": "R.E.P.O.",
    "deep rock galactic.exe": "Deep Rock Galactic",
    "fsd-win64-shipping.exe": "Deep Rock Galactic",
    "fallguys_client_game.exe": "Fall Guys",
    "fallguys.exe": "Fall Guys",
    "gangbeasts.exe": "Gang Beasts",
    "human fall flat.exe": "Human: Fall Flat",
    "ittakestwo.exe": "It Takes Two",
    "asplitfiction.exe": "Split Fiction",
    "splitfiction.exe": "Split Fiction",
    "splitfiction-win64-shipping.exe": "Split Fiction",
    "raftclient.exe": "Raft",
    "raft.exe": "Raft",
    "goose game.exe": "Untitled Goose Game",
    "untitled goose game.exe": "Untitled Goose Game",
    "partyanimals-win64-shipping.exe": "Party Animals",
    "overcooked2.exe": "Overcooked! 2",
    "overcooked.exe": "Overcooked!",
    "plateup.exe": "PlateUp!",
    "powerwashsimulator.exe": "PowerWash Simulator",
    "houseflipper.exe": "House Flipper",

    # Story / narrative / immersive
    "disco elysium.exe": "Disco Elysium",
    "discoelysium.exe": "Disco Elysium",
    "outer wilds.exe": "Outer Wilds",
    "outerwilds.exe": "Outer Wilds",
    "the outer worlds.exe": "The Outer Worlds",
    "outerworlds.exe": "The Outer Worlds",
    "theouterworlds2.exe": "The Outer Worlds 2",
    "scorngame.exe": "Scorn",
    "pentiment.exe": "Pentiment",
    "talosprincipal.exe": "The Talos Principle",
    "talosprincipal2.exe": "The Talos Principle 2",
    "twelveminutes.exe": "Twelve Minutes",
    "what remains of edith finch.exe": "What Remains of Edith Finch",
    "firewatch.exe": "Firewatch",
    "death stranding.exe": "Death Stranding",
    "dsdirectorscut.exe": "Death Stranding: Director's Cut",
    "days gone.exe": "Days Gone",
    "daysgone.exe": "Days Gone",
    "the last of us part i.exe": "The Last of Us Part I",
    "tlou-i.exe": "The Last of Us Part I",
    "tlou-ii.exe": "The Last of Us Part II",
    "persona5r.exe": "Persona 5 Royal",
    "persona5royal.exe": "Persona 5 Royal",
    "persona3r.exe": "Persona 3 Reload",
    "persona4golden.exe": "Persona 4 Golden",
    "metaphorrefantazio.exe": "Metaphor: ReFantazio",
    "metaphor.exe": "Metaphor: ReFantazio",
    "yakuza.exe": "Yakuza",
    "like a dragon.exe": "Like a Dragon",
    "likeadragon.exe": "Like a Dragon",
    "likeadragoninfinitewealth.exe": "Like a Dragon: Infinite Wealth",
    "judgment.exe": "Judgment",
    "lostjudgment.exe": "Lost Judgment",
    "finalfantasyxvi.exe": "Final Fantasy XVI",
    "ff16.exe": "Final Fantasy XVI",
    "finalfantasyxvi-win64-shipping.exe": "Final Fantasy XVI",
    "finalfantasyviiremake.exe": "Final Fantasy VII Remake",
    "finalfantasy7rebirth.exe": "Final Fantasy VII Rebirth",
    "ff7rebirth.exe": "Final Fantasy VII Rebirth",
    "nierautomata.exe": "NieR: Automata",
    "nierreplicant.exe": "NieR Replicant",
    "octopathtraveler.exe": "Octopath Traveler",
    "octopathtraveler2.exe": "Octopath Traveler II",

    # Live service / gacha
    "wuthering waves.exe": "Wuthering Waves",
    "wuthering waves game.exe": "Wuthering Waves",
    "genshinimpact.exe": "Genshin Impact",
    "yuanshen.exe": "Genshin Impact",
    "genshinimpact-win64-shipping.exe": "Genshin Impact",
    "zenlesszonezero.exe": "Zenless Zone Zero",
    "zzz.exe": "Zenless Zone Zero",
    "zzz-win64-shipping.exe": "Zenless Zone Zero",
    "honkaistarrail.exe": "Honkai: Star Rail",
    "starrail.exe": "Honkai: Star Rail",
    "starrail-win64-shipping.exe": "Honkai: Star Rail",

    # Classics
    "quake.exe": "Quake",
    "quake2.exe": "Quake II",
    "quake3arena.exe": "Quake III Arena",
    "ioquake3.exe": "Quake III Arena",
    "hl2.exe": "Half-Life 2",
    "halflife.exe": "Half-Life",
    "halflife2.exe": "Half-Life 2",
    "halflifealyx.exe": "Half-Life: Alyx",
    "portal.exe": "Portal",
    "portal2.exe": "Portal 2",
    "l4d2.exe": "Left 4 Dead 2",
    "left4dead2.exe": "Left 4 Dead 2",
    "left4dead.exe": "Left 4 Dead",
    "tf_win64.exe": "Team Fortress 2",
    "tf2.exe": "Team Fortress 2",
    "garrysmod.exe": "Garry's Mod",
    "gmod.exe": "Garry's Mod",
    "hl2_win64.exe": "Half-Life 2",
    "diablo iv.exe": "Diablo IV",
    "diablo iv launcher.exe": "Diablo IV",
    "diablo iii.exe": "Diablo III",
    "diablo ii.exe": "Diablo II",
    "diablo ii resurrected.exe": "Diablo II: Resurrected",
    "d2r.exe": "Diablo II: Resurrected",
    "thebindingofisaac.exe": "The Binding of Isaac",
    "isaac-ng.exe": "The Binding of Isaac: Rebirth",
    "ftl.exe": "FTL: Faster Than Light",
    "fasterthanlight.exe": "FTL: Faster Than Light",
    "mountandblade.exe": "Mount & Blade",

    # Misc popular
    "animal well.exe": "Animal Well",
    "animalwell.exe": "Animal Well",
    "dredge.exe": "Dredge",
    "tinyglade.exe": "Tiny Glade",
    "davethediver.exe": "Dave the Diver",
    "pizzatower.exe": "Pizza Tower",
    "bombrushcyberfunk.exe": "Bomb Rush Cyberfunk",
    "chainedtogether.exe": "Chained Together",
    "onlyup.exe": "Only Up!",
    "peak.exe": "Peak",
    "peak-win64-shipping.exe": "Peak",
    "stray.exe": "Stray",
    "stray-win64-shipping.exe": "Stray",
    "spiritfarer.exe": "Spiritfarer",
    "coral island.exe": "Coral Island",
    "coralisland-win64-shipping.exe": "Coral Island",
    "webfishing.exe": "Webfishing",
    "tunic.exe": "Tunic",
    "cocoon.exe": "Cocoon",

    # Launchers (you usually want to know your game, not the launcher, but
    # mapping them here keeps the toast sensible if recording does fire on them)
    "steam.exe": "Steam",
    "epicgameslauncher.exe": "Epic Games Launcher",
    "ealauncher.exe": "EA App",
    "eadesktop.exe": "EA App",
    "gog galaxy.exe": "GOG Galaxy",
    "ubisoftconnect.exe": "Ubisoft Connect",
    "battle.net.exe": "Battle.net",
    "battle.net launcher.exe": "Battle.net",
}


# Suffixes commonly added by Unreal, EAC, etc. that we strip before fallback.
_STRIP_SUFFIXES: tuple[str, ...] = (
    "-Win64-Shipping", "-Win32-Shipping", "_Shipping",
    "_DX12", "_DX11", "_Vulkan", "_BE", "_EAC", "_x64",
)


# Words that the title-caser should keep as-is (acronyms etc.).
_KEEP_WORDS = {
    "FFXIV", "FFXI", "MMO", "MOBA", "FPS", "RPG",
    "DLC", "VR", "AR", "VR.",
    "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
    "MK", "GTA", "RDR", "DOS",
}


def humanise_game_name(exe_name: str) -> str:
    """Return a friendly display name for the given executable basename.

    Looks up :data:`_DISPLAY_NAMES` first (case-insensitive). Falls back to a
    cleanup heuristic: strip .exe + known launcher suffixes, replace
    separators, split camelCase, title-case.
    """
    if not exe_name:
        return exe_name
    key = exe_name.lower()
    if key in _DISPLAY_NAMES:
        return _DISPLAY_NAMES[key]

    # Fallback: clean up the raw exe.
    name = exe_name[:-4] if exe_name.lower().endswith(".exe") else exe_name
    for suffix in _STRIP_SUFFIXES:
        if name.endswith(suffix):
            name = name[: -len(suffix)]
            break
    # Normalise separators
    name = name.replace("_", " ").replace("-", " ")
    # camelCase -> camel Case (insert space before uppercase that follows lowercase
    # or that's followed by lowercase as part of a new word, e.g. "ABCWord" -> "ABC Word")
    name = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", name)
    name = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", name)
    # Collapse repeated spaces
    name = re.sub(r"\s+", " ", name).strip()
    if not name:
        return exe_name

    # Title-case with acronym preservation.
    words = []
    for w in name.split(" "):
        if w.upper() in _KEEP_WORDS:
            words.append(w.upper())
        elif w.isupper() and len(w) >= 2:
            # All-caps token (likely an acronym) — keep.
            words.append(w)
        else:
            words.append(w[:1].upper() + w[1:])
    return " ".join(words)


# Recordings produced by the session manager are named
# "<game-slug>_YYYY-MM-DD_HHMMSS[.<ext>][_clip_N.mp4]". Regex captures the
# slug — i.e. everything up to (but not including) the timestamp.
_FILENAME_PREFIX_RE = re.compile(r"^(.+?)_\d{4}-\d{2}-\d{2}_\d{6}")


def game_slug_from_filename(filename: str) -> str | None:
    """Return the game-slug prefix (e.g. ``ffxiv_dx11``) or None on no match."""
    m = _FILENAME_PREFIX_RE.match(filename)
    return m.group(1) if m else None


def friendly_recording_title(filename: str) -> str:
    """Title for a recording file as shown in the recordings list.

    Maps the slug through :func:`humanise_game_name`. If the file is an
    exported trim (``..._clip_N.mp4``), appends ``" — Clip N"``. Falls
    back to the bare stem when the filename doesn't follow the recorder's
    naming convention.
    """
    from pathlib import Path

    p = Path(filename)
    stem = p.stem
    slug = game_slug_from_filename(p.name)
    if slug is None:
        return stem
    title = humanise_game_name(slug + ".exe")
    # _clip_N suffix on exported trims.
    clip_match = re.search(r"_clip_(\d+)$", stem)
    if clip_match:
        title = f"{title} — Clip {clip_match.group(1)}"
    return title
